name: notification
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  provider: ^6.1.2
  flutter_timezone: ^2.0.0
  http: ^1.2.1
  percent_indicator: ^4.2.3
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
